spring.application.name=praktikum1

spring.jpa.hibernate.ddl-auto = update
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.diver-class-name=com.mysql.cj.jdbc.Driver

spring.config.import=file:.env[.properties]